name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push openvpn-server
        uses: docker/build-push-action@v2
        with:
          file: Dockerfiles/Dockerfile-php-runtime
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openvpn-server:2.4
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/openvpn-server
      -
        name: Build and push openvpn-admin
        uses: docker/build-push-action@v2
        with:
          file: Dockerfiles/Dockerfile-openvpn-admin
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openvpn-admin:php-7.1.33-apache-stretch
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/openvpn-admin